luafile ~/.config/nvim/lua/general.lua
luafile ~/.config/nvim/lua/plugins.lua
luafile ~/.config/nvim/lua/plug-config/manson.lua
luafile ~/.config/nvim/lua/lsp/general.lua
luafile ~/.config/nvim/lua/plug-config/lspsaga-config.lua
luafile ~/.config/nvim/lua/plug-config/telescope-config.lua
luafile ~/.config/nvim/lua/plug-config/cmp-config.lua
luafile ~/.config/nvim/lua/plug-config/notify-config.lua
luafile ~/.config/nvim/maps.lua
luafile ~/.config/nvim/lua/plug-config/general.lua
luafile ~/.config/nvim/lua/plug-config/lualine-config.lua
